/**
 * Seed: 03_projects.js
 * Complete dataset of 175 Projects extracted from "PROJECT LIST AND SUPERVISOR REQUIREMENT (1).xlsx"
 */

function parseStatus(supervisorText, supRequired, nosA) {
  if (!supervisorText || supervisorText.trim() === '') {
    return (supRequired && supRequired > 0) ? 'needs_supervisor' : 'pending';
  }
  const t = supervisorText.toUpperCase().trim();
  if (t.includes('COMPLETED GROUTING PENDING')) return 'grouting_pending';
  if (t.startsWith('COMPLETED')) return 'completed';
  if (t.startsWith('STOPPED')) return 'stopped';
  if (t.startsWith('STRENGTHENING')) return 'strengthening';
  if (t.includes('SUPERVISOR REQUIRED')) return 'needs_supervisor';
  if (t === 'MODEL ENGG') return 'pending';
  return (nosA && nosA > 0) ? 'active' : 'pending';
}

const ALL_175_PROJECTS = [
  { folder_no:'109', ak_job_no:'AK-23-037', project_name:'Iraz Properties Sky Wall Contracting', area_sqft:15559, supervisor_names:'VENKADESHWAR GOUD', supervisors_assigned:1 },
  { folder_no:'121', ak_job_no:'AK-23-256', project_name:'JULFAR CONTRACTING PLOT 002', area_sqft:24263, supervisor_names:'DINESH KUMAR NORTH', supervisors_assigned:1 },
  { folder_no:'146', ak_job_no:'AK-24-381', project_name:'Indo Gulf Contracting AK-23-452 Januss P185', area_sqft:17663, supervisor_names:'MANIGOVINDASAMY', supervisors_assigned:1 },
  { folder_no:'151', ak_job_no:'AK-23-278', project_name:'Abdul Azizi', area_sqft:87078, supervisor_names:'RAMAN ALAGAPPAN, DURAI PALANI, RAMKI MANIKKAM, CHINNADURAI PERIYASAMY, VENKATESH SAKTHIVEL, VIGNESWARAN', supervisors_assigned:6 },
  { folder_no:'162', ak_job_no:'AK-23-136', project_name:'Tiger Renald Tower 2B+G&M+4P+37F+R', area_sqft:47458, supervisor_names:'SIVASANKAR, SIVAKUMAR PERUMAL', supervisors_assigned:2 },
  { folder_no:'175', ak_job_no:'Ak-24-257', project_name:'Tiger Volga Tower', area_sqft:89718, supervisor_names:'MANIKANDAN AYYASAMY', supervisors_assigned:1 },
  { folder_no:'178', ak_job_no:'AK-24-23', project_name:'Bin Malek Contracting', area_sqft:3539, supervisor_names:'STOPPED', supervisors_assigned:0 },
  { folder_no:'183', ak_job_no:'AK-24-173', project_name:'Modern Building Contracting 3B+G+17 Arjan (Samana)', area_sqft:51302, supervisor_names:'RAMAR SADAYAN, AKASH', supervisors_assigned:1, supervisors_available_march:2 },
  { folder_no:'190', ak_job_no:'AK-24-110', project_name:'Samana Ivy Garden - Modern Contracting', area_sqft:44862, supervisor_names:'Eslam Soliman, Youssef', supervisors_assigned:2 },
  { folder_no:'193', ak_job_no:'AK-24-132', project_name:'Indo Gulf G+1P+10TYP', area_sqft:27732, supervisor_names:'COMPLETED GROUTING PENDING', supervisors_assigned:0 },
  { folder_no:'209', ak_job_no:'AK-24-433', project_name:'Loft Contracting PLOT NO.IC3-E-04', area_sqft:6502, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'219a', ak_job_no:'', project_name:'Pivot Reems Hills [Abu Dhabi] - A', area_sqft:181191, supervisor_names:'SELVAMANI A, MOHAMMAD ASHRAF (Hassan) ALI', supervisors_assigned:2 },
  { folder_no:'219b', ak_job_no:'', project_name:'Pivot Reems Hills [Abu Dhabi] - B', area_sqft:null, supervisor_names:'SENTHIL KUMAR, DINESH MARUDAI, MANI SANYASI', supervisors_assigned:3 },
  { folder_no:'219c', ak_job_no:'', project_name:'Pivot Reems Hills [Abu Dhabi] - C', area_sqft:null, supervisor_names:'Mohamed Badr, Sr Badr, Chinnasamy Massy', supervisors_assigned:3 },
  { folder_no:'219d', ak_job_no:'', project_name:'Pivot Reems Hills [Abu Dhabi] - D', area_sqft:null, supervisor_names:'SURESH KANDAN, TAGA', supervisors_assigned:2, supervisors_available_march:3 },
  { folder_no:'220', ak_job_no:'AK-24-572', project_name:'Model Consultant (B+G+5P+38+R)', area_sqft:43818, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'229', ak_job_no:'AK-24-592 (186)', project_name:'INDO GULF CONTRACTING + Emsquare P186', area_sqft:11154, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'229', ak_job_no:'AK-24-592 (187)', project_name:'INDO GULF CONTRACTING + Emsquare P187', area_sqft:7930, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'230', ak_job_no:'AK-24-609', project_name:'Model- Wog Capital, G+P+6+R', area_sqft:10302, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'232', ak_job_no:'AK-24-599', project_name:'Buildtech Construction', area_sqft:9940, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'233', ak_job_no:'AK-25-009', project_name:'Shine Square, G+4+R', area_sqft:8127, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'234', ak_job_no:'AK-24-316', project_name:'Costplus Contracting G+4+ROOF', area_sqft:6025, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'236', ak_job_no:'AK-24-482', project_name:'Model Engg, G+2P+8+R', area_sqft:24290, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'237', ak_job_no:'AK-24-447', project_name:'NSE Contracting G+3P+17+R', area_sqft:36726, supervisor_names:'Palani Muthu', supervisors_assigned:1 },
  { folder_no:'238', ak_job_no:'AK-23-383', project_name:'Al Tawoos Contr. G+P+6+R', area_sqft:14661, supervisor_names:'Muthu Mayakannan', supervisors_assigned:1 },
  { folder_no:'239', ak_job_no:'Ak-24-422', project_name:'ITEC Const 2B+G+10+R', area_sqft:18750, supervisor_names:'Gameel, MEGADY', supervisors_assigned:2 },
  { folder_no:'242', ak_job_no:'AK-24-375', project_name:'Hamec Consultant - WAHEEDA', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'243', ak_job_no:'AK-25-049', project_name:'Al Rabat Cont. 1B+G+1P+13+R', area_sqft:19533, supervisor_names:'Ali Mahroos, Ahmed Farha', supervisors_assigned:2 },
  { folder_no:'246', ak_job_no:'AK-24-59', project_name:'Al Shafar Helix Tower', area_sqft:22993, supervisor_names:'Moustfa em, Ahmed Mahmoud, ESALAM SAAD', supervisors_assigned:3 },
  { folder_no:'247', ak_job_no:'AK-24-661', project_name:'Model Consultant P-772 - 2B+G+11+M+R Sky Island', area_sqft:10494, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'249', ak_job_no:'AK-24-526', project_name:'Al Shafar G+1 Comm', area_sqft:4128, supervisor_names:'PALANIMUTHU', supervisors_assigned:1, supervisors_available_march:1 },
  { folder_no:'250', ak_job_no:'AK-25-070', project_name:'DSCA Luminar 1 - (152475)', area_sqft:25334, supervisor_names:'Manikandan Marimuttu', supervisors_assigned:1 },
  { folder_no:'250', ak_job_no:'AK-25-070', project_name:'DSCA Luminar 2 - (151731)', area_sqft:25375, supervisor_names:'Kandan Narayansamy', supervisors_assigned:1 },
  { folder_no:'251', ak_job_no:'AK-25-061', project_name:'DSCA Luminar 3', area_sqft:20649, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'252', ak_job_no:'AK-25-041', project_name:'Sumer Cont, B+G+9+R', area_sqft:40122, supervisor_names:'RAJARAJAN GOVINDARAJ, AYMAN', supervisors_assigned:2 },
  { folder_no:'253', ak_job_no:'AK-25-089', project_name:'Allied Cont. B+G+M+4+R', area_sqft:5774, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'254', ak_job_no:'AK-24-642', project_name:'NAJ Contracting G+1', area_sqft:723, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'255', ak_job_no:'AK-25-133', project_name:'MUNAWEL INTERIORS Strengthening', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'256', ak_job_no:'AK-24-536', project_name:'City Experts-Burjeel Hospital- (Strengthening)', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'257', ak_job_no:'AK-25-111A', project_name:'ASHIYANA CONTRACTING (Site#281) G+3P+12+R', area_sqft:24020, supervisor_names:'EZHUMALAI SAMIDURAI', supervisors_assigned:1, supervisors_available_march:1 },
  { folder_no:'257', ak_job_no:'AK-25-111B', project_name:'ASHIYANA CONTRACTING (Site#282) B+G+9+R', area_sqft:24253, supervisor_names:'SEMMALAI GOVINDAN', supervisors_assigned:1, supervisors_available_march:1 },
  { folder_no:'258', ak_job_no:'AK-25-018', project_name:'ITAL TECH Samana B+G+4P+27+PH.FR (Hilal Conslt) - BV01', area_sqft:72057, supervisor_names:'AYYAPPAN, VANNIYADEVAN', supervisors_assigned:2 },
  { folder_no:'259', ak_job_no:'AK-25-074', project_name:'ITAL TECH Samana B+G+P+11+R (AREC)', area_sqft:23791, supervisor_names:'MARIMUTHU PARAMASIVAM', supervisors_assigned:1 },
  { folder_no:'260', ak_job_no:'AK-24-621', project_name:'Lamida Contracting G+3P+19F+R', area_sqft:47971, supervisor_names:'SAKTHIVEL PERIYASAMU & AJAY PRASAD', supervisors_assigned:2 },
  { folder_no:'261', ak_job_no:'AK-25-042', project_name:'INDO GULF P188 G+1P+5+R', area_sqft:18276, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'268', ak_job_no:'AK-25-097', project_name:'ARAB CONTRACTS', area_sqft:7147, supervisor_names:'PAPPU CHUNNU PRASAD', supervisors_assigned:1 },
  { folder_no:'269', ak_job_no:'AK-25-190', project_name:'Tiger Al Furjan 7', area_sqft:32011, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'', ak_job_no:'AK-25-190', project_name:'Tiger Al Furjan 8', area_sqft:20339, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'270', ak_job_no:'AK-25-164', project_name:'Dsca Ozone Project B+G+4P+21+R', area_sqft:24342, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'272', ak_job_no:'AK-24-637', project_name:'Skada Construction G+2P+8', area_sqft:12440, supervisor_names:'SENDAMARIA KANDAN', supervisors_assigned:1, supervisors_available_march:1 },
  { folder_no:'273', ak_job_no:'AK-25-093', project_name:'Atcon Construction + Chawla Architects', area_sqft:194707, supervisor_names:'5 SUPERVISOR, 6 TECHNICIAN', supervisors_assigned:0, supervisors_required:5, technicians_required:6 },
  { folder_no:'274', ak_job_no:'AK-25-185', project_name:'Tekton Construction + Renaissance conslt', area_sqft:7543, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'275', ak_job_no:'AK-25-243', project_name:'MIAMI Contr + Modular design consult', area_sqft:5242, supervisor_names:'', supervisors_assigned:1 },
  { folder_no:'276', ak_job_no:'AK-25-188', project_name:'CHC Dubai Police', area_sqft:4740, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'278', ak_job_no:'AK-25-285', project_name:'KTC INTERNATIONAL L.L.C', area_sqft:8120, supervisor_names:'COMPLETED, GROUTING IS PENDING', supervisors_assigned:1 },
  { folder_no:'280', ak_job_no:'AK-25-218', project_name:'CHICAGO Contr + Mimar Architect', area_sqft:8719, supervisor_names:'KRISHNA', supervisors_assigned:1, supervisors_available_march:1 },
  { folder_no:'281', ak_job_no:'AK-25-230', project_name:'Baron Contracting + Model Engg Consult', area_sqft:8123, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'282', ak_job_no:'AK-24-598', project_name:'Modern Cube Contr + Bait Alomor PMC', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'283', ak_job_no:'AK-25-305', project_name:'Grand Signature bldg. Paramjit', area_sqft:1350, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'', ak_job_no:'', project_name:'Grand Signature bldg. Rishi', area_sqft:2087, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'284', ak_job_no:'AK-25-354', project_name:'Loft Contracting 3B+G+12+R', area_sqft:35543, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'285', ak_job_no:'AK-25-024', project_name:'Thapar Home B+G+1+R', area_sqft:1985, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'286', ak_job_no:'AK-25-211', project_name:'Model P762 G+2p+12+R', area_sqft:28467, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'287', ak_job_no:'AK-24-199', project_name:'Ritz Contracting', area_sqft:6368, supervisor_names:'MURUGAN CHANDRAN', supervisors_assigned:1 },
  { folder_no:'288', ak_job_no:'AK-25-368', project_name:'Loft Contr. B+G+6+R', area_sqft:12501, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'289', ak_job_no:'AK-25-303', project_name:'SS Lootah Contracting', area_sqft:369, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'292', ak_job_no:'AK-25-347', project_name:'G+3P+19+R Model', area_sqft:28863, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'293', ak_job_no:'AK-25-269', project_name:'Onix Plus', area_sqft:463, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'295', ak_job_no:'AK-24-575', project_name:'UG+G+5P+32 Al Hikma Bldg cont', area_sqft:39865, supervisor_names:'PRAVEEN GANESH', supervisors_assigned:1 },
  { folder_no:'296', ak_job_no:'AK-25-466', project_name:'City Experts', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'297', ak_job_no:'AK-25-224', project_name:'Al Saad Bldg cont', area_sqft:1120, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'298', ak_job_no:'AK-25-439', project_name:'Injaz Al Madina', area_sqft:38341, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'299', ak_job_no:'AK-25-297', project_name:'Grand Signature', area_sqft:369, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'300', ak_job_no:'AK-25-471', project_name:'G+2 Villa, Kanzalard Bldg C', area_sqft:806, supervisor_names:'MANIGOVINDASAMY', supervisors_assigned:1 },
  { folder_no:'301', ak_job_no:'AK-25-229', project_name:'Model Engg', area_sqft:6613, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'302', ak_job_no:'AK-25-472', project_name:'Shaanxi', area_sqft:14896, supervisor_names:'Vinoth Kumar + Perisamy Kannan', supervisors_assigned:2 },
  { folder_no:'303', ak_job_no:'AK-25-453', project_name:'AQUBE VEGA TOWER', area_sqft:15959, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'304', ak_job_no:'AK-25-095', project_name:'DNA', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'305', ak_job_no:'AK-25-451', project_name:'Injaz Al Madina 3-2', area_sqft:7379, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'306', ak_job_no:'AK-25-452', project_name:'Injaz Al Madina 3-3', area_sqft:9221, supervisor_names:'COMPLETED', supervisors_assigned:0 },
  { folder_no:'307', ak_job_no:'AK-25-222', project_name:'Aashiyana_Jadaf', area_sqft:8870, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'308', ak_job_no:'AK-25-476', project_name:'Forces Bldg Contracting', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'309', ak_job_no:'AK-25-254', project_name:'Luxridge Contracting', area_sqft:83755, supervisor_names:'Muthu Marimuthu, SURENDAR KUMAR', supervisors_assigned:2 },
  { folder_no:'310', ak_job_no:'AK-25-431', project_name:'G+2P+10, Well Concept', area_sqft:16239, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'311', ak_job_no:'AK-25-609', project_name:'B+G+2P+21 Al Masood Nat', area_sqft:29133, supervisor_names:'Ramesh Kannan, HOSSAM', supervisors_assigned:2 },
  { folder_no:'313', ak_job_no:'AK-24-656', project_name:'G+5P+35+R TAK CONST', area_sqft:36952, supervisor_names:'NEPPOLIYAN', supervisors_assigned:1 },
  { folder_no:'314', ak_job_no:'AK-25-209', project_name:'G+P+5+R Crystal Cont', area_sqft:9553, supervisor_names:'Pankaj', supervisors_assigned:1 },
  { folder_no:'315', ak_job_no:'AK-25-481', project_name:'G+2P+12 Resi Bldg - MODEL ENGG', area_sqft:22981, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'317', ak_job_no:'AK-25-415', project_name:'B+G+5 Naf Cont', area_sqft:10393, supervisor_names:'Ram Bahadur', supervisors_assigned:1 },
  { folder_no:'318', ak_job_no:'AK-25-286', project_name:'Atcon Arena Towers', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'319', ak_job_no:'AK-24-601', project_name:'Hassan Allam Const RAK', area_sqft:31638, supervisor_names:'DONGA VENKAT, 1 SUPERVISOR REQUIRED', supervisors_assigned:1, supervisors_required:1 },
  { folder_no:'320', ak_job_no:'AK-25-116', project_name:'B+G+1 Villa Jessr Cont', area_sqft:1938, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'321', ak_job_no:'Ak-24-628', project_name:'Walk Thru Contracting', area_sqft:1679, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'322', ak_job_no:'AK-25-688', project_name:'Golden Wall Villa 26', area_sqft:880, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'323', ak_job_no:'AK-25-550', project_name:'G+4+Roof, BIN Malek', area_sqft:2218, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'324', ak_job_no:'AK-25-724', project_name:'G+B+4P+26F+R Model Engg', area_sqft:51500, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'325', ak_job_no:'AK-25-405', project_name:'G+P+12F TA + 12F TB', area_sqft:28131, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'326', ak_job_no:'AK-25-632', project_name:'G+2P+8', area_sqft:14311, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'327', ak_job_no:'AK-25-351', project_name:'SS Lootah Contracting', area_sqft:4989, supervisor_names:'TamilaRasan', supervisors_assigned:1 },
  { folder_no:'328', ak_job_no:'AK-25-213', project_name:'Private Villa Al Alawneh', area_sqft:4212, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'329', ak_job_no:'AK-25-715', project_name:'B+G+P+9 RAK - MODEL ENGG', area_sqft:26247, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'330', ak_job_no:'AK-25-725', project_name:'B+G+2P+10+R MODEL', area_sqft:21500, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'331', ak_job_no:'AK-25-761', project_name:'DHCN G+4 VILLA', area_sqft:10376, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'332', ak_job_no:'AK-25', project_name:'AL BAIT ENG CONSLT', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'333', ak_job_no:'AK-25-689', project_name:'BARARI VIEWS 2 SAMANA', area_sqft:67247, supervisor_names:'ANNAMALAI A+Raja Arumugam', supervisors_assigned:2 },
  { folder_no:'334', ak_job_no:'AK-25-810', project_name:'AMMON CONTRACTNG', area_sqft:2118, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'335', ak_job_no:'AK-25-708', project_name:'RAK Academy - Chicago', area_sqft:9306, supervisor_names:'2 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:2 },
  { folder_no:'336', ak_job_no:'AK-25-495', project_name:'B+G+13 Design Hub DLRC', area_sqft:19547, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'337', ak_job_no:'AK-25-712', project_name:'G+1 TEKTON', area_sqft:1196, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'338', ak_job_no:'AK-25-448', project_name:'B+G+M & G+1+R Casais', area_sqft:10982, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'339', ak_job_no:'AK-031', project_name:'SHINE SQUARE', area_sqft:5774, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'340', ak_job_no:'AK-25-089', project_name:'ALLIED', area_sqft:5774, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'341', ak_job_no:'AK-25-487', project_name:'1B+G+2P+15 TAK', area_sqft:null, supervisor_names:'Arun Kumar', supervisors_assigned:1 },
  { folder_no:'342', ak_job_no:'AK-25-752', project_name:'AL SHAFAR G+3P+19+R', area_sqft:41386, supervisor_names:'Mahmood Samy, Mathesh', supervisors_assigned:2 },
  { folder_no:'343', ak_job_no:'AK-25-548', project_name:'AL QAHERA', area_sqft:12015, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'344', ak_job_no:'AK-25-718', project_name:'AECS', area_sqft:53228, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'345', ak_job_no:'AK-25-877', project_name:'G+4 BIN MALEK', area_sqft:2120, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'346', ak_job_no:'Ak-25-872', project_name:'1B+G+1P+13+R Rabat', area_sqft:18649, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'347', ak_job_no:'AK-25-759', project_name:'G+GP+15TYP INJAZ', area_sqft:25400, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'348', ak_job_no:'AK-25-865', project_name:'B+G+5P+50+R Tiger', area_sqft:85565, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'349', ak_job_no:'AK-25-894 -T1', project_name:'2B+G+M+(15+18+21)+R Tiger T1', area_sqft:113559, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'349', ak_job_no:'AK-25-894 -T2', project_name:'2B+G+M+(15+18+21)+R Tiger T2', area_sqft:112664, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'350', ak_job_no:'AK-25-884', project_name:'G+3P+13 Golden Bldg Cont.', area_sqft:16988, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'351', ak_job_no:'AK-25-837', project_name:'G+P+6+R Autolink', area_sqft:12343, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'352', ak_job_no:'AK-25-438', project_name:'G+3P+4+R Al Maeraj Cont.', area_sqft:11668, supervisor_names:'SURENDRA BABU', supervisors_assigned:1 },
  { folder_no:'353', ak_job_no:'AK-25-946', project_name:'Villa 606-707 Strengthening', area_sqft:null, supervisor_names:'STRENGTHENING', supervisors_assigned:0 },
  { folder_no:'354', ak_job_no:'AK-25-840', project_name:'B+G+3P+19+R Lux Ridge', area_sqft:113960, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:2, supervisors_required:1 },
  { folder_no:'355', ak_job_no:'AK-25-047', project_name:'2B+G+10P+37+R Tiger', area_sqft:108865, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'356', ak_job_no:'AK-25-786', project_name:'G+3P+20F+R TAK Const', area_sqft:26588, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'357', ak_job_no:'AK-25-954', project_name:'G+2P+6TYP+R Golden Bldg', area_sqft:10902, supervisor_names:'Jai Kumar+1 SUPERVISOR REQUIRED', supervisors_assigned:1, supervisors_required:1 },
  { folder_no:'358', ak_job_no:'AK-25-931', project_name:'G+3P+4+R NAF', area_sqft:18282, supervisor_names:'Saminathan Pazhni', supervisors_assigned:1 },
  { folder_no:'359', ak_job_no:'AK-25-758', project_name:'G+1P+6+R Indo Gulf', area_sqft:9585, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'360', ak_job_no:'AK-25-667', project_name:'G+8+R NAF', area_sqft:17583, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'361', ak_job_no:'AK-25-960', project_name:'2B+G+19 CEG CAPITAL ONE', area_sqft:45318, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'362', ak_job_no:'AK-25-904', project_name:'1-13, ROOF, sola', area_sqft:36316, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'363', ak_job_no:'AK-25-844', project_name:'CITY EXPERTS', area_sqft:5858, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'364', ak_job_no:'AK-25-955', project_name:'B+G+4 ARABCO', area_sqft:6121, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'365', ak_job_no:'AK-25-984', project_name:'HK TWIN TOWER-0137', area_sqft:15153, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'365', ak_job_no:'AK-25-984', project_name:'HK TWIN TOWER-0138', area_sqft:15152, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'366', ak_job_no:'AK-25-964', project_name:'TONINI', area_sqft:36910, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'367', ak_job_no:'AK-25-945', project_name:'WOODCO', area_sqft:1407, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'368', ak_job_no:'AK-25-540', project_name:'FAJA', area_sqft:28256, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'369', ak_job_no:'AK-25-249', project_name:'G+4 RE-22 Uniforce', area_sqft:6059, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'370', ak_job_no:'AK-25-702', project_name:'Wedding Hall Aroma', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'371', ak_job_no:'AK-25-996', project_name:'Bond Interiors', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'372', ak_job_no:'AK-25-1004', project_name:'Golden Wall Villas (18,19,20,25,28,30,44,49)', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'373', ak_job_no:'AK-25-1006', project_name:'G+1+R DIRHAM Cont', area_sqft:1283, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'374', ak_job_no:'AK-25-881', project_name:'DWC AMANA', area_sqft:5854, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'375', ak_job_no:'AK-25-532', project_name:'G+1 Villa MBC', area_sqft:351, supervisor_names:'Vishwa', supervisors_assigned:1 },
  { folder_no:'376', ak_job_no:'AK-25-1062', project_name:'G+4 STAFF SAM Bldg Cont.', area_sqft:8560, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'377', ak_job_no:'AK-25-1007', project_name:'High Beam Villa 909', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'378', ak_job_no:'AK-25-1023', project_name:'B+G+8+R Globecon', area_sqft:26376, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'379', ak_job_no:'AK-25-295', project_name:'B+G+1 Ankora Shafar Villa', area_sqft:1743, supervisor_names:'Palanisamy Pachamuthu', supervisors_assigned:1 },
  { folder_no:'380', ak_job_no:'AK-25-1121', project_name:'G+2P+ 14TA+14TB', area_sqft:30065, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'381', ak_job_no:'AK-25-1050', project_name:'B+G+1 NAF', area_sqft:3170, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'382', ak_job_no:'AK-25-1022', project_name:'G+4+R Shine Square', area_sqft:6375, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'383', ak_job_no:'AK-25-1056', project_name:'B+G+1+R StroyGarant', area_sqft:1932, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'384', ak_job_no:'AK-25-968', project_name:'G+6+R Abaj Cont.', area_sqft:7024, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'385', ak_job_no:'AK-25-1117', project_name:'G+4+R Abaj Cont', area_sqft:5391, supervisor_names:'1 SUPERVISOR REQUIRED', supervisors_assigned:0, supervisors_required:1 },
  { folder_no:'386', ak_job_no:'AK-25-763', project_name:'B+G+9 Jeikor', area_sqft:18242, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'387', ak_job_no:'AK-24-258', project_name:'B+G+4P+28+R Jade Tiger', area_sqft:58229, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'388', ak_job_no:'AK-25-1126', project_name:'P+G+4F+R InjazM Warsan', area_sqft:5380, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'389', ak_job_no:'AK-25-1045', project_name:'2B+G+13+R Autolink Seraph', area_sqft:16136, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'390', ak_job_no:'AK-25-1060', project_name:'G+P+6 Ocean Pearl1', area_sqft:15525, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'391', ak_job_no:'AK-25-1061', project_name:'G+P+6 Ocean Pearl2', area_sqft:null, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'392', ak_job_no:'AK-25-1097', project_name:'G+4P+15+R Luxridge', area_sqft:73475, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'393', ak_job_no:'AK-25-853', project_name:'G+4 Janus Model', area_sqft:9082, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'394', ak_job_no:'AK-26-019', project_name:'G+2P+10+R OST', area_sqft:8724, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'395', ak_job_no:'AK-25-1070', project_name:'G+4P+31+Mech+R Luxridge', area_sqft:210664, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'396', ak_job_no:'AK-25-704', project_name:'B+G+5+R ROME 1', area_sqft:6895, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'397', ak_job_no:'AK-25-1089', project_name:'G+2P+8+R Shine Square', area_sqft:15619, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'398', ak_job_no:'AK-25-1101', project_name:'G+4F+R Loft', area_sqft:10844, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'399', ak_job_no:'AK-25-766', project_name:'G+1F Al Awir', area_sqft:572, supervisor_names:'', supervisors_assigned:0 },
  { folder_no:'400', ak_job_no:'AK-26-020', project_name:'G+4 Al Maeraj', area_sqft:9297, supervisor_names:'', supervisors_assigned:0 }
];

exports.seed = async function(knex) {
  await knex('projects').del();

  const rows = ALL_175_PROJECTS.map(p => ({
    folder_no: p.folder_no || null,
    ak_job_no: p.ak_job_no || null,
    project_name: p.project_name,
    area_sqft: p.area_sqft || null,
    supervisor_names: p.supervisor_names || null,
    supervisors_assigned: p.supervisors_assigned || 0,
    supervisors_required: p.supervisors_required || 0,
    technicians_required: p.technicians_required || 0,
    supervisors_available_march: p.supervisors_available_march || 0,
    status: parseStatus(p.supervisor_names, p.supervisors_required || 0, p.supervisors_assigned || 0),
    is_active: true,
  }));

  await knex('projects').insert(rows);
  console.log(`✅ Seeded all ${rows.length} projects into database`);
};
